compile:
	g++ main.cpp ./src/schrodinger.cpp ./include/Schrodinger.hpp -larmadillo -o main

run_P7_1:
	./main input_P7_1

run_P7_2:
	./main input_P7_2

run_P8:
	./main input_P8

run_P9_single:
	./main input_P9_single

run_P9_double:
	./main input_P9_double

run_P9_triple:
	./main input_P9_triple

run_all:
	./main input_P7_1
	./main input_P7_2
	./main input_P8
	./main input_P9_single
	./main input_P9_double
	./main input_P9_triple


